version: "3.2"
services:
  web_dev:
    build: .
    ports:
      - "4000:4000"
      - "27018:27017"
    volumes:
      - .:/usr/src/app
    environment:
      - ENV=development
      - PORT=4000
      - DB=mongodb://mongodb:27017/bhaskarDB
      - MY_API_KEY_FOREX=vBNPGoabV5FyTlgv1WA1IuKPX5ZaybbJ
      - MY_API_KEY_HIST=a396917c6b46215ad0578d2312ad6f10
      - SECRET='secret-key'
  mongodb:
    image: mongo:latest
    container_name: "mongodbDev"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
networks:
  default:
    name: web_dev
