apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - args:
        - mongod
        - --smallfiles
        - --logpath=/dev/null
        env:
        - name: MONGO_DATA_DIR
          value: /usr/data/db
        - name: MONGO_LOG_DIR
          value: /dev/null
        image: mongo:latest
        name: mongodbdev
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /usr/data/db
          name: mongodb-claim0
      restartPolicy: Always
      volumes:
      - name: mongodb-claim0
        persistentVolumeClaim:
          claimName: mongodb-claim0
status: {}
