apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: web-dev
  name: web-dev
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: web-dev
    spec:
      containers:
      - image: web-dev
        name: web-dev
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
